project:
  type: website
  resources:
    - "files/"

execute:
  # Re-render only when source changes
  freeze: auto

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

website:
  title: "Bayesian statistics"

  repo-url: https://github.com/andrewheiss/bayesf22.classes.andrewheiss.com
  repo-actions: [edit, issue]

  navbar:
    pinned: true
    background: dark
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd


format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
